import * as fs from 'node:fs';
import * as path from 'node:path';
import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as handlebars from 'handlebars';
import * as nodemailer from 'nodemailer';

/**
 * Sends transactional emails via Nodemailer using Handlebars templates.
 *
 * In production (`STAGE=production`) the transporter uses Gmail SMTP with an
 * app password. In all other environments it creates an Ethereal test account
 * and logs a preview URL so emails can be inspected without a real SMTP server.
 *
 * Templates live in `src/modules/email/templates/*.hbs` and are compiled at
 * send time. Each `send*` method compiles the appropriate template with its
 * variables and delegates to the private `send()` helper.
 */
@Injectable()
export class EmailService {
  private transporter: nodemailer.Transporter;

  constructor(private configService: ConfigService) {
    if (this.configService.get<string>('STAGE') === 'production') {
      this.transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
          user: this.configService.get<string>('GMAIL_USER'),
          pass: this.configService.get<string>('GMAIL_APP_PASSWORD'),
        },
      });
    } else {
      this.initEthereal();
    }
  }

  // ── Transport setup ──────────────────────────────────────────────────────

  /** Creates an Ethereal SMTP transporter for non-production environments. */
  private async initEthereal() {
    const testAccount = await nodemailer.createTestAccount();
    this.transporter = nodemailer.createTransport({
      host: 'smtp.ethereal.email',
      port: 587,
      secure: false,
      auth: { user: testAccount.user, pass: testAccount.pass },
    });
  }

  // ── Public send methods ──────────────────────────────────────────────────

  /** Sends a magic-link sign-in email. The link expires per the JWT config. */
  async sendMagicLink(
    to: string,
    firstName: string,
    link: string,
  ): Promise<void> {
    const html = this.compileTemplate('magic-link', { firstName, link });
    await this.send(to, 'Your magic link to sign in', html);
  }

  /** Sends a welcome email after successful account registration. */
  async sendWelcomeEmail(to: string, firstName: string): Promise<void> {
    const html = this.compileTemplate('welcome', { firstName });
    await this.send(to, 'Welcome to BeOrchid!', html);
  }

  /** Notifies the farmer of a new disease or yield prediction on their farm. */
  async sendPredictionAlert(
    to: string,
    firstName: string,
    farmName: string,
    summary: string,
  ): Promise<void> {
    const html = this.compileTemplate('prediction-alert', { firstName, farmName, summary });
    await this.send(to, `Prediction Alert — ${farmName}`, html);
  }

  /** Notifies the farmer of a health alert generated by the health pipeline. */
  async sendHealthAlert(
    to: string,
    firstName: string,
    farmName: string,
    summary: string,
  ): Promise<void> {
    const html = this.compileTemplate('health-alert', { firstName, farmName, summary });
    await this.send(to, `Health Alert — ${farmName}`, html);
  }

  /** Confirms subscription activation after a successful Paystack payment. */
  async sendSubscriptionActivated(
    to: string,
    firstName: string,
    planName: string,
    summary: string,
  ): Promise<void> {
    const html = this.compileTemplate('subscription-activated', { firstName, planName, summary });
    await this.send(to, `Your ${planName} plan is now active`, html);
  }

  /** Delivers the randomly generated super-admin credentials created by `AdminSeedService`. */
  async sendSuperAdminCredentials(to: string, firstName: string, email: string, password: string): Promise<void> {
    const html = this.compileTemplate('super-admin-credentials', { firstName, email, password });
    await this.send(to, 'Your BeOrchid Super Admin credentials', html);
  }

  /** Notifies the farmer that their farm has completed the full setup flow. */
  async sendFarmSetupComplete(
    to: string,
    firstName: string,
    farmName: string,
  ): Promise<void> {
    const html = this.compileTemplate('farm-setup-complete', { firstName, farmName });
    await this.send(to, `${farmName} setup is complete`, html);
  }

  // ── Helpers ──────────────────────────────────────────────────────────────

  /** Reads and compiles a Handlebars template from the `templates/` directory. */
  private compileTemplate(name: string, context: object): string {
    const templatePath = path.join(__dirname, 'templates', `${name}.hbs`);
    const source = fs.readFileSync(templatePath, 'utf-8');
    return handlebars.compile(source)(context);
  }

  /** Sends a compiled HTML email via the configured Nodemailer transporter. */
  private async send(to: string, subject: string, html: string) {
    const info = await this.transporter.sendMail({
      from: this.configService.get<string>('EMAIL_FROM'),
      to,
      subject,
      html,
    });
    console.log('Email sent: %s', info.messageId);
    const preview = nodemailer.getTestMessageUrl(info);
    if (preview) console.log('Preview URL: %s', preview);
  }
}
